@startuml packages_Nutrify
set namespaceSeparator none
package "backend" as backend {
}
package "backend.app" as backend.app {
}
package "backend.controller" as backend.controller {
}
package "backend.controller.food_controller" as backend.controller.food_controller {
}
package "backend.controller.health_controller" as backend.controller.health_controller {
}
package "backend.controller.user_auth" as backend.controller.user_auth {
}
package "backend.data_layer" as backend.data_layer {
}
package "backend.data_layer.Models" as backend.data_layer.Models {
}
package "backend.data_layer.Models.food_model" as backend.data_layer.Models.food_model {
}
package "backend.data_layer.Models.health_model" as backend.data_layer.Models.health_model {
}
package "backend.data_layer.Models.model" as backend.data_layer.Models.model {
}
package "backend.data_layer.Models.user_model" as backend.data_layer.Models.user_model {
}
package "backend.data_layer.repository" as backend.data_layer.repository {
}
package "backend.data_layer.repository.db" as backend.data_layer.repository.db {
}
package "backend.data_layer.repository.food_repository" as backend.data_layer.repository.food_repository {
}
package "backend.data_layer.repository.health_repository" as backend.data_layer.repository.health_repository {
}
package "backend.data_layer.repository.jaro" as backend.data_layer.repository.jaro {
}
package "backend.data_layer.repository.user_repository" as backend.data_layer.repository.user_repository {
}
package "backend.view" as backend.view {
}
package "backend.view.config" as backend.view.config {
}
backend.app --> backend.controller.food_controller
backend.app --> backend.controller.health_controller
backend.app --> backend.controller.user_auth
backend.app --> backend.data_layer.repository.food_repository
backend.app --> backend.view.config
backend.data_layer.Models.food_model --> backend.data_layer.Models.model
backend.data_layer.Models.health_model --> backend.data_layer.Models.model
backend.data_layer.Models.health_model --> backend.data_layer.Models.user_model
backend.data_layer.Models.user_model --> backend.data_layer.Models.model
backend.data_layer.repository.food_repository --> backend.data_layer.repository.db
backend.data_layer.repository.food_repository --> backend.data_layer.repository.jaro
backend.data_layer.repository.health_repository --> backend.data_layer.repository.user_repository
backend.data_layer.repository.user_repository --> backend.data_layer.repository.db
@enduml